### PR TITLE
support elastic (6.7.1) and pymorphy2-dicts-ru (2.4.404381.4453942)

### PR DESCRIPTION
**Pull request by maksaimer**
Added new versions of elasticsearch and pymorphy2-dicts-ru

### CODE REVIEW

**Comment by anti-social** [comment]
I'm on vacation at the moment. Will see PR after the weekend.

**Comment by anti-social** [comment]
Fixed tests: https://github.com/anti-social/jmorphy2/pull/21

**Comment by anti-social** [comment]
You can find assembled plugin in a bintray repository: https://bintray.com/evo/elasticsearch/jmorphy2-elasticsearch/0.2.1#files

Or install it directly from repo:

**Comment by maksaimer** [comment]
Thank you

**Pull request merged**
